# Generated by Django 5.2.5 on 2025-08-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('parent_pid', models.IntegerField(blank=True, null=True)),
                ('snapshot_time', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='process_monitor.machine')),
            ],
            options={
                'indexes': [models.Index(fields=['machine', 'snapshot_time'], name='process_mon_machine_5b7b89_idx')],
            },
        ),
    ]
